export default {
    "keys": [
        "Tartes flambées",
        "La traditionnelle",
        "Crème, lardons, oignons",
        "La gratinée",
        "Crème, lardons, oignons, [émmental]",
        "La champignon",
        "Crème, lardons, oignons, Champignon",
        "La Forestière",
        "Crème, lardons, oignons, champignon, [émmental]",
        "La [Munster]",
        "Crème, lardons, oignons, [munster]",
        "La [Ribeaupierre]",
        "Crème, lardons, oignons, [ribeaupierre]",
        "La Basque",
        "Crème, lardons, oignons, brebis",
        "La chèvre",
        "Crème, lardons, oignons, chèvre",
        "La formule",
        "une tarte classique + 1 verre de vin",
        "Nos salades",
        "Tomates Mozza",
        "cœur de crème burrata 200 grammes",
        "La vigneronne",
        "cervelas alsacien, pomme de terre, tomates, salade, cornichon, sauce maison, raisins secs, herbes",
        "Salade de la mer",
        "salade, tomate, œuf, thon, truites fumées ou saumon herbes (selon arrivage)",
        "Salade végétarienne",
        "Salade, tomate, maïs, asperges, steack végétarien",
        "Tartare de bœuf",
        "viande hachée, échalote, jaune d’œuf, câpres, sauces",
        "Les classiques Alsaciens",
        "Choucroute garnie",
        "(5 éléments) saucisse fumée, [Knack], salé de porc, lards, pomme de terre, choux Crème, lardons, oignons",
        "Jarret de porc",
        "entre 600 et 750 grammes braisé avec accompagnement",
        "Jarret de porc au [munster]",
        "entre 600 et 750 grammes braisé au [munster]",
        "Beakeoffe",
        "viande de bœuf, porc et agneau marinées au vin blanc, pomme de terre, carottes.",
        "Pâté en croute Alsacien",
        "avec légumes",
        "Fromage de tête ",
        "Quiche Lorraine",
        "Tarte à l’oignon",
        "Assiettes de foie gras",
        "2 tranches de foie gras, confiture, pains, 1 verre de vendange tardive",
        "Planchette mixte",
        "[gendarme], jambon fumé, [chorizo], jambon du sud ouest, fuet, [munster], [ribeaupierre], brebis, cornichon, beurre, confiture cerise",
        "Assiette de fromage",
        "[Munster], [ribeaupierre], brebis, confiture, cumin",
        "Menu enfant",
        "frites [Knacks]",
        "bol de salade",
        "assiette de frites",
        "NOTRE TOMATES MOZZA",
        "LA PLANCHETTE MIXTE",
        "NOS TARTES FLAMBÉES",
        "LA CHÈVRE",
        "QUICHE LORRAINE",
        "LA TARTE À L’OIGNON",
        "LE TARTARE DE BŒUF"
    ],
    "fr": [
        "Tartes flambées",
        "La traditionnelle",
        "Crème, lardons, oignons",
        "La gratinée",
        "Crème, lardons, oignons, émmental",
        "La champignon",
        "Crème, lardons, oignons, Champignon",
        "La Forestière",
        "Crème, lardons, oignons, champignon, émmental",
        "La Munster",
        "Crème, lardons, oignons, munster",
        "La Ribeaupierre",
        "Crème, lardons, oignons, ribeaupierre",
        "La Basque",
        "Crème, lardons, oignons, brebis",
        "La chèvre",
        "Crème, lardons, oignons, chèvre",
        "La formule",
        "une tarte classique + 1 verre de vin",
        "Nos salades",
        "Tomates Mozza",
        "cœur de crème burrata 200 grammes",
        "La vigneronne",
        "cervelas alsacien, pomme de terre, tomates, salade, cornichon, sauce maison, raisins secs, herbes",
        "Salade de la mer",
        "salade, tomate, œuf, thon, truites fumées ou saumon herbes (selon arrivage)",
        "Salade végétarienne",
        "Salade, tomate, maïs, asperges, steack végétarien",
        "Tartare de bœuf",
        "viande hachée, échalote, jaune d’œuf, câpres, sauces",
        "Les classiques Alsaciens",
        "Choucroute garnie",
        "(5 éléments) saucisse fumée, Knack, salé de porc, lards, pomme de terre, choux Crème, lardons, oignons",
        "Jarret de porc",
        "entre 600 et 750 grammes braisé avec accompagnement",
        "Jarret de porc au munster",
        "entre 600 et 750 grammes braisé au munster",
        "Beakeoffe",
        "viande de bœuf, porc et agneau marinées au vin blanc, pomme de terre, carottes.",
        "Pâté en croute Alsacien",
        "avec légumes",
        "Fromage de tête ",
        "Quiche Lorraine",
        "Tarte à l’oignon",
        "Assiettes de foie gras",
        "2 tranches de foie gras, confiture, pains, 1 verre de vendange tardive",
        "Planchette mixte",
        "gendarme, jambon fumé, chorizo, jambon du sud ouest, fuet, munster, ribeaupierre, brebis, cornichon, beurre, confiture cerise",
        "Assiette de fromage",
        "Munster, ribeaupierre, brebis, confiture, cumin",
        "Menu enfant",
        "frites Knacks",
        "bol de salade",
        "assiette de frites",
        "NOTRE TOMATES MOZZA",
        "LA PLANCHETTE MIXTE",
        "NOS TARTES FLAMBÉES",
        "LA CHÈVRE",
        "QUICHE LORRAINE",
        "LA TARTE À L’OIGNON",
        "LE TARTARE DE BŒUF"
    ],
    "en": [
        "Flamboyant pies",
        "The traditional",
        "Cream, bacon, onions",
        "The au gratin",
        "Cream, bacon, onions, émmental",
        "The mushroom",
        "Cream, bacon, onions, mushroom",
        "The Forest",
        "Cream, bacon, onions, mushroom, émmental",
        "The Munster",
        "Cream, bacon, onions, munster",
        "The Ribeaupierre",
        "Cream, bacon, onions, ribeaupierre",
        "Basque",
        "Cream, bacon, onions, ewes",
        "The goat",
        "Cream, bacon, onions, goat cheese",
        "The formula",
        "a classic pie + 1 glass of wine",
        "Our salads",
        "Tomatoes Mozza",
        "heart of burrata cream 200 grams",
        "The winemaker",
        "Alsatian saucepan, potato, tomatoes, salad, gherkin, homemade sauce, raisins, herbs",
        "Salad From The Sea",
        "salad, tomato, egg, tuna, smoked trout or salmon herbs (according to arrival)",
        "Vegetarian salad",
        "Salad, tomato, corn, asparagus, vegetarian steak",
        "Bovine Tartar",
        "minced meat, shallot, egg yolk, capers, sauces",
        "The Alsatian classics",
        "Sauerkraut",
        "(5 items) Smoked sausage, Knack, salted pork, bacon, potato, cream puffs, bacon, onions",
        "Pork knuckle",
        "between 600 and 750 grams braised with accompaniment",
        "Pork knuckle at munster",
        "between 600 and 750 grams braised at munster",
        "Beakeoffe",
        "beef, pork and lamb marinated in white wine, potatoes, carrots.",
        "Alsatian crusted pâté",
        "with vegetables",
        "Head cheese",
        "Quiche Lorraine",
        "Onion tart",
        "Plates of foie gras",
        "2 slices of foie gras, jam, breads, 1 glass of late harvest",
        "Mixed board",
        "gendarme, smoked ham, chorizo, south west ham, fuet, munster, ribeaupierre, ewe, gherkin, butter, cherry jam",
        "Cheese plate",
        "Munster, ribeaupierre, sheep, jam, caraway",
        "Children's menu",
        "fries Knacks",
        "bowl of salad",
        "plate of French fries",
        "OUR TOMATO MOZZA",
        "THE JOINT PLANCHETTE",
        "OUR DARK PITS",
        "THE GOAT",
        "QUICHE LORRAINE",
        "THE ONION PIE",
        "THE BEEF TARTARE"
    ],
    "es": [
        "Pasteles extravagantes",
        "El tradicional",
        "Crema, tocino, cebollas",
        "El gratinado",
        "Crema, tocino, cebollas, émmental",
        "El hongo",
        "Crema, tocino, cebolla, champiñón",
        "El bosque",
        "Crema, tocino, cebolla, champiñón, émmental",
        "El Munster",
        "Crema, tocino, cebollas, munster",
        "El Ribeaupierre",
        "Crema, tocino, cebollas, ribeaupierre",
        "Vasco",
        "Crema, tocino, cebollas, ovejas",
        "La cabra",
        "Crema, tocino, cebolla, queso de cabra",
        "La formula",
        "un clásico pastel + 1 copa de vino",
        "Nuestras ensaladas",
        "Tomates Mozza",
        "corazón de crema de burrata 200 gramos",
        "El enólogo",
        "Cacerola alsaciana, patata, tomate, ensalada, pepinillo, salsa casera, pasas, hierbas",
        "Ensalada de mar",
        "ensalada, tomate, huevo, atún, trucha ahumada o hierbas de salmón (según llegada)",
        "Ensalada vegetariana",
        "Ensalada, tomate, maíz, espárragos, filete vegetariano",
        "Tartare de ternera",
        "carne picada, chalote, yema de huevo, alcaparras, salsas",
        "Los clásicos alsacianos",
        "Chucrut adornado",
        "(5 artículos) Salchicha ahumada, Knack, cerdo salado, tocino, patatas, hojaldre de crema, tocino, cebolla",
        "Nudillo de cerdo",
        "entre 600 y 750 gramos estofado con acompañamiento",
        "Nudillo de cerdo en munster",
        "entre 600 y 750 gramos estofado en munster",
        "Beakeoffe",
        "carne de res, cerdo y cordero marinado en vino blanco, papas, zanahorias.",
        "Paté con costra alsaciana",
        "con vegetales",
        "Cabeza de queso",
        "Quiche Lorraine",
        "Tarta de cebolla",
        "Platos de foie gras",
        "2 rebanadas de foie gras, mermelada, panes, 1 vaso de última cosecha",
        "Tablero mixto",
        "gendarme, jamón ahumado, chorizo, jamón del sudoeste, fuet, munster, ribeaupierre, oveja, pepinillo, mantequilla, confitura de cerezas",
        "Plato de queso",
        "Munster, ribeaupierre, oveja, mermelada, alcaravea",
        "Menú para niños",
        "papas fritas Knacks",
        "plato de ensalada",
        "plato de papas fritas",
        "NUESTRO TOMATE MOZZA",
        "EL PLANCHETTE CONJUNTO",
        "NUESTRAS OLAS OSCURAS",
        "LA CABRA",
        "QUICHE LORRAINE",
        "EL pastel de cebolla",
        "EL TARTARE DE CARNE"
    ],
    "de": [
        "Flamboyant Kuchen",
        "Das Traditionelle",
        "Sahne, Speck, Zwiebeln",
        "Das Gratin",
        "Sahne, Speck, Zwiebeln, émmental",
        "Der Pilz",
        "Sahne, Speck, Zwiebeln, Pilze",
        "Der Wald",
        "Sahne, Speck, Zwiebeln, Pilze, émmental",
        "Der Munster",
        "Sahne, Speck, Zwiebeln, munster",
        "Der Ribeaupierre",
        "Sahne, Speck, Zwiebeln, ribeaupierre",
        "Baskisch",
        "Sahne, Speck, Zwiebeln, Mutterschafe",
        "Die Ziege",
        "Sahne, Speck, Zwiebeln, Ziegenkäse",
        "Die Formel",
        "eine klassische Torte + 1 Glas Wein",
        "Unsere Salate",
        "Tomaten Mozza",
        "Herz von Burrata Creme 200 Gramm",
        "Der Winzer",
        "Elsässischer Kochtopf, Kartoffeln, Tomaten, Salat, Gurke, hausgemachte Soße, Rosinen, Kräuter",
        "Salat des Meeres",
        "Salat, Tomate, Ei, Thunfisch, geräucherte Forelle oder Lachskräuter (nach Ankunft)",
        "Vegetarischer Salat",
        "Salat, Tomate, Mais, Spargel, vegetarisches Steak",
        "Beef Tartar",
        "Hackfleisch, Schalotten, Eigelb, Kapern, Saucen",
        "Die elsässischen Klassiker",
        "Garniertes Sauerkraut",
        "(5 Artikel) Geräucherte Wurst, Knack, gesalzenes Schweinefleisch, Speck, Kartoffel, Windbeutel, Speck, Zwiebeln",
        "Eisbein",
        "zwischen 600 und 750 Gramm mit Begleitung geschmort",
        "Eisbein bei munster",
        "zwischen 600 und 750 Gramm geschmort bei munster",
        "Beakeoffe",
        "Rind, Schwein und Lamm mariniert in Weißwein, Kartoffeln, Karotten.",
        "Elsässisch verkrustete Pastete",
        "mit Gemüse",
        "Kopf Käse",
        "Quiche Lorraine",
        "Zwiebelkuchen",
        "Teller mit Gänseleber",
        "2 Scheiben Foie Gras, Marmelade, Brot, 1 Glas Spätlese",
        "Mischbrett",
        "gendarme, geräucherter Schinken, chorizo, Südwestschinken, Fuet, munster, ribeaupierre, Schaf, Gurke, Butter, Kirschmarmelade",
        "Käseplatte",
        "Munster, ribeaupierre, Schaf, Marmelade, Kümmel",
        "Kindermenü",
        "Pommes Knacks",
        "Schüssel Salat",
        "Teller mit Pommes frites",
        "UNSERE TOMATE MOZZA",
        "DIE GEMEINSAME PLANCHETTE",
        "UNSERE DARK PITS",
        "Der Ziege",
        "Quiche Lorraine",
        "DIE ZWIEBELTORTE",
        "DER RIND TARTARE"
    ],
    "zh-CN": [
        "华丽的馅饼",
        "传统",
        "奶油，培根，洋葱",
        "自动搅拌器",
        "奶油，培根，洋葱，émmental",
        "蘑菇",
        "奶油，培根，洋葱，蘑菇",
        "森林",
        "奶油，培根，洋葱，蘑菇，émmental",
        "Munster",
        "奶油，培根，洋葱，munster",
        "Ribeaupierre",
        "奶油，培根，洋葱，ribeaupierre",
        "巴斯克",
        "奶油，培根，洋葱，母羊",
        "山羊",
        "奶油，培根，洋葱，山羊奶酪",
        "公式",
        "一杯经典的派+一杯葡萄酒",
        "我们的沙拉",
        "西红柿Mozza",
        "burrata奶油心脏200克",
        "酿酒师",
        "阿尔萨斯平底锅，土豆，西红柿，沙拉，小黄瓜，自制酱，葡萄干，草药",
        "海的沙拉",
        "沙拉，番茄，鸡蛋，金枪鱼，熏鳟鱼或三文鱼草药（根据抵达）",
        "素食沙拉",
        "沙拉，西红柿，玉米，芦笋，素食牛排",
        "鞑靼牛肉",
        "肉末，葱，蛋黄，刺山柑，酱汁",
        "阿尔萨斯经典",
        "腌制酸菜",
        "（5项）熏香肠，Knack，咸猪肉，培根，土豆，奶油泡芙，培根，洋葱",
        "猪肉指关节",
        "600克至750克与伴奏炖",
        "猪肉指关节munster",
        "600克和750克之间munster",
        "Beakeoffe",
        "牛肉，猪肉和羊肉腌制白葡萄酒，土豆，胡萝卜。",
        "阿尔萨斯结痂的香肠",
        "与蔬菜",
        "头奶酪",
        "乳蛋饼洛林",
        "洋葱馅饼",
        "鹅肝酱",
        "2片鹅肝，果酱，面包，1杯晚收",
        "混合板",
        "gendarme，熏火腿，chorizo，西南火腿，奶酪，munster，ribeaupierre，母羊，小黄瓜，黄油，樱桃果酱",
        "奶酪盘子",
        "Munster，ribeaupierre，羊，果酱，香菜",
        "儿童菜单",
        "薯条Knacks",
        "一碗沙拉",
        "炸薯条板材",
        "我们的番茄莫扎佐",
        "联合计划",
        "我们的黑暗坑",
        "山羊",
        "QUICHE LORRAINE",
        "洋葱馅饼",
        "牛肉TARTARE"
    ]
};